make libtool usage dependent on target
And be explicit about --without-python

Error in windows:
```/workspace/destdir/x86_64-w64-mingw32/lib/../lib/libstdc++.la: No such file or directory```
It comes from this Travis job: https://travis-ci.org/JuliaGeo/GDALBuilder/jobs/515658089#L639

Error --without-libtool on Linux:
However that breaks the `i686-linux-gnu` and `x86_64-linux-gnu` builds with `undefined reference to `__dso_handle'`: https://travis-ci.org/JuliaGeo/GDALBuilder/jobs/518166189#L638-L640
(which might be a compiler bug)